project_id               = "google account project id"
storage_int              = "strorage integration service account"
notification_integration = "notification integration service account"
org_name                 = "snowflake organization name"
account_name             = "snowflake account name"
username                 = "snowflake username"
password                 = "snowflake password"
