project_id       = "google account project id"
email            = "email used to authenticate with google cloud"
org_name         = "snowflake organization name"
account_name     = "snowflake account name"
username         = "snowflake username"
password         = "snowflake password"
notification_int = "notification integration name"